# Uncomment the next line to define a global platform for your project
 platform :macos, 10.15

target 'MyTodoList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Starscream'
  pod 'Swifter'
  pod 'Nimble'
  
  target 'FunctionsTest' do
       inherit! :search_paths
   end
end
